export const projectData = { "projects" : [
    {
      name: "The Lion's Roar Website",
      dir: "tlr_website",
      desktop_thumbnail: "/tlr_intro/desk_thumbnail.png",
      mobile_thumbnail: "/tlr_intro/mobile_thumbnail.png",
      category: "Web Development",
      tags: ["React", "Google Cloud", "Next.js"],
      accentColor: "#000000",
      grid_span: "3",
    },
    {
      name: "The Lion's Roar Intro",
      dir: "tlr_intro",
      desktop_thumbnail: "/tlr_intro/Intro_Main_1.mp4",
      mobile_thumbnail: "/tlr_intro/mobile_thumbnail.png",
      category: "3D-Rendering",
      tags: ["After Effects", "Blender"],
      accentColor: "#000000",
      grid_span: "2",
    },
    {
      name: "Crystal Cave (Dynamic Machines)",
      dir: "crystal_caves",
      desktop_thumbnail: "/crystal_caves/LoopingFinal.mp4",
      mobile_thumbnail: "/tlr_intro/mobile_thumbnail.png",
      category: "3D-Rendering",
      tags: ["After Effects", "Substance 3D Painter", "Blender"],
      accentColor: "#bcffb1",
      grid_span: "1",
    },
]};